version: "3.9"

services:
  
  api: 
    build: .
    container_name: banking-api
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://admin:admin@postgres:5432/banking_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      QUEUE_RETRY_INTERVAL_MS: 5000
    ports:
      - "3000:3000"
  
  worker:
    build: .
    container_name: banking-worker
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/banking_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      MAX_RETRIES: 3
      RETRY_DELAY_MS: 5000
      WORKER_RECONNECT_MS: 5000
    command: npm run worker
  notification-worker:
    build: .
    container_name: banking-notification-worker
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - webhook-receiver
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/banking_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      WORKER_RECONNECT_MS: 5000
      NOTIFICATION_MAX_RETRIES: 3
      NOTIFICATION_RETRY_DELAY_MS: 5000
      NOTIFICATION_WEBHOOK_URL: http://webhook-receiver:4000/notifications
    command: npm run notification-worker
  webhook-receiver:
    build: ./webhook-receiver
    container_name: banking-webhook-receiver
    restart: always
    environment:
      PORT: 4000
    ports:
      - "4000:4000"
  postgres:
    image: postgres:15
    container_name: banking-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: banking_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: banking-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
